# Generated by Django 4.2.11 on 2024-04-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_change_remove_stock_percent_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='full_time_employees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='long_business_summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('esg_score', models.FloatField()),
                ('carbon_footprint', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('net_income', models.BigIntegerField()),
                ('total_revenue', models.BigIntegerField()),
                ('ebit', models.BigIntegerField()),
                ('operating_income', models.BigIntegerField()),
                ('interest_expense', models.BigIntegerField()),
                ('earnings_before_tax', models.BigIntegerField()),
                ('operating_cashflow', models.BigIntegerField()),
                ('investment_cashflow', models.BigIntegerField()),
                ('total_assets', models.BigIntegerField()),
                ('total_liabilities', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='stocks.stock')),
            ],
            options={
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
