# Generated by Django 4.2.11 on 2024-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_full_time_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financials',
            name='data_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='financials',
            name='period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
