# Generated by Django 4.2.11 on 2024-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_financials_earnings_before_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='earnings_before_tax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='ebit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='interest_expense',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='investment_cashflow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='net_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='operating_cashflow',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='operating_income',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_liabilities',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_revenue',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
